# See: https://github.com/artob/readmer#template-variables
---
label: URLcache
title: URLcache
summary:
  URLcache fetches HTTP responses with deduped offline caching layered on top of Bitcache content-addressable storage.
